python train.py \
    --data_root ./datasets/train/samples \
    --annotations ./datasets/train/annotations/annotations.json \
    --test_data_root ./datasets/test/samples \
    --test_annotations ./datasets/test/annotations/annotations.json \
    --stage 2 \
    --epochs 150 \
    --n_way 2 \
    --n_query 4 \
    --num_aug 3 \
    --n_episodes 500 \
    --use_triplet \
    --triplet_ratio 0.3 \
    --negative_strategy mixed \
    --triplet_batch_size 32 \
    --use_batch_hard_triplet \
    --lr 2e-5 \
    --weight_decay 0.005 \
    --gradient_accumulation 1 \
    --mixed_precision \
    --num_workers 1 \
    --checkpoint_dir ./checkpoints/stage2 \
    --save_interval 5 \
    --bbox_weight 7.5 \
    --cls_weight 0.5 \
    --dfl_weight 0.15 \
    --supcon_weight 1.2 \
    --cpe_weight 0.6 \
    --triplet_weight 0.3 \
    --yolo_weights ./models/base/yolov8-n.pt \
    --dinov3_model vit_small_patch16_dinov3.lvd1689m \
    --freeze_dinov3 \
    --use_wandb \
    --wandb_project ZALO \
    --wandb_entity it-dainb \
    --wandb_name stage_2_gradient_fix \
    --val_st_iou_cache  ./datasets/test/annotations/ \
    --gradient_clip_norm 5.0